services:

  mongodb:
    image: mongo:8.0.13-noble
    container_name: ${MONGO_INITDB_DATABASE}
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - ./app/database/init-db.js:/docker-entrypoint-initdb.d/init-db.js
    networks:
      - fastapi-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: ${MONGO_INITDB_DATABASE}-frontend
    restart: always
    ports:
      - "8081:8081"
    networks:
      - fastapi-network
    environment:
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      ME_CONFIG_MONGODB_PORT: ${ME_CONFIG_MONGODB_PORT}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_OPTIONS_EDITORTHEME: ${ME_CONFIG_OPTIONS_EDITORTHEME}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${ME_CONFIG_MONGODB_AUTH_DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${ME_CONFIG_MONGODB_AUTH_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${ME_CONFIG_MONGODB_AUTH_PASSWORD}
      ME_CONFIG_SITE_SESSIONSECRET: ${ME_CONFIG_SITE_SESSIONSECRET}
    depends_on:
      - mongodb

  fastapi:
    image: "fastapi-mongodb:0.1.0"
    container_name: "fastapi-mongodb"
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - fastapi-network
    environment:
      SECRET_KEY: ${SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    depends_on:
      - mongodb
      - mongo-express

volumes:
  mongo-data:
  mongo-config:

networks:
  fastapi-network:
    driver: bridge
